Alter UTF-8 handling for compatibility with AWS SES
This fixes the following error:
  ckan.lib.mailer.MailerException: SMTPDataError(554, b"Transaction failed: Missing final '@domain'")

AWS SES only supports RFC-822 presently and does not play nicely with
UTF-8

See: https://github.com/ckan/ckan/issues/5704
See: https://trello.com/c/ggOr2250/1429-email-to-zendesk-from-user-membership-requests-is-broken-following-ckan-upgrade